name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # Checks out the repository’s code

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      # Logs in to Docker Hub using the credentials stored in GitHub 
Secrets

    - name: Build Docker image
      run: |
        docker build -t somayeteymurifar/api:latest .
      # Builds the Docker image and tags it as 
'somayeteymurifar/api:latest'

    - name: Push Docker image
      run: |
        docker push somayeteymurifar/api:latest
      # Pushes the Docker image to Docker Hub

