name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        SHORT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-7)
        echo "Short Hash: $SHORT_HASH"
        docker build -t somayeteymurifar/api:$SHORT_HASH 

    - name: Push Docker image
      run: |
        SHORT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-7)
        echo "Short Hash: $SHORT_HASH"
        docker push somayeteymurifar/api:$SHORT_HASH



